#!/bin/sh
terraform show -json \
  | jq '{resources:[ .values.root_module.resources[] 
    | .type as $type 
    | .name as $name 
    | .values |{$type,id,$name} ]}' \
  | pulumi import -f /dev/stdin --yes


